### ISSUE TITLE
Health Bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [Alf21/ttt2-role_vamp#1]
While using the latest GitHub version I think that the vampire's bloodlust mode is broken or bugged, hitting someone while it's active randomly gives or takes away hp from the player. Going back to the old workshop version fixed the issue but the vampire doesn't have a cap on his health and can gain infinite health

This is a video of the bug
https://youtu.be/yzUbW0MraoU

**Comment by Alf21** [comment]
Ty, I‘m going to fix it later
